exclude: '.git'
default_stages: [commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-merge-conflict
        exclude: /README\.rst$|^docs/.*\.rst$
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  # - repo: https://github.com/PyCQA/isort
  #   rev: 5.5.1
  #   hooks:
  #     - id: isort
  #       name: isort except __init__.py
  #       args:
  #         - --settings=.
  #       exclude: /__init__\.py$
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        name: pylint with mandatory checks
        verbose: true
        args:
          - --score=y
#           - --disable=E0611,E0401,R0914,R0915,W0703,E1101,C0103,R0912,duplicate-code
          - --const-naming-style=snake_case
          - --rcfile=.pylintrc
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]
